# 基础镜像
FROM redis
# author
MAINTAINER xingqiao

# 挂载目录
VOLUME /home/xingqiao/redis
# 创建目录
RUN mkdir -p /home/xingqiao/redis
# 指定路径
WORKDIR /home/xingqiao/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/xingqiao/redis/redis.conf
