# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER xingqiao

# 挂载目录
VOLUME /home/xingqiao
# 创建目录
RUN mkdir -p /home/xingqiao
# 指定路径
WORKDIR /home/xingqiao
# 复制jar文件到路径
COPY ./jar/xingqiao-modules-file.jar /home/xingqiao/xingqiao-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","xingqiao-modules-file.jar"]