# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER xingqiao

# 挂载目录
VOLUME /home/xingqiao
# 创建目录
RUN mkdir -p /home/xingqiao
# 指定路径
WORKDIR /home/xingqiao
# 复制jar文件到路径
COPY ./jar/xingqiao-gateway.jar /home/xingqiao/xingqiao-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","xingqiao-gateway.jar"]